"use client";

/* eslint-disable react-hooks/exhaustive-deps */
import { CSSProperties, ReactNode, useEffect, useId, useRef, useState } from "react";
import "./GlassSurface.css";

type BlendMode = "normal" | "multiply" | "screen" | "overlay" | "darken" | "lighten" | "difference" | "exclusion" | "hue" | "saturation" | "color" | "luminosity";
type Channel = "R" | "G" | "B";
type Props = { children?: ReactNode; width?: number | string; height?: number | string; borderRadius?: number; borderWidth?: number; brightness?: number; opacity?: number; blur?: number; displace?: number; backgroundOpacity?: number; saturation?: number; distortionScale?: number; redOffset?: number; greenOffset?: number; blueOffset?: number; xChannel?: Channel; yChannel?: Channel; mixBlendMode?: BlendMode; className?: string; style?: CSSProperties };

export default function GlassSurface({ children, width=200, height=80, borderRadius=20, borderWidth=.07, brightness=50, opacity=.93, blur=11, displace=0, backgroundOpacity=0, saturation=1, distortionScale=-180, redOffset=0, greenOffset=10, blueOffset=20, xChannel="R", yChannel="G", mixBlendMode="difference", className="", style={} }: Props) {
  const uniqueId=useId().replace(/:/g,"-"); const filterId=`glass-filter-${uniqueId}`; const redGradId=`red-grad-${uniqueId}`; const blueGradId=`blue-grad-${uniqueId}`;
  const [svgSupported,setSvgSupported]=useState(false); const containerRef=useRef<HTMLDivElement>(null); const feImageRef=useRef<SVGFEImageElement>(null); const redRef=useRef<SVGFEDisplacementMapElement>(null); const greenRef=useRef<SVGFEDisplacementMapElement>(null); const blueRef=useRef<SVGFEDisplacementMapElement>(null); const blurRef=useRef<SVGFEGaussianBlurElement>(null);
  const generateMap=()=>{ const rect=containerRef.current?.getBoundingClientRect(); const w=rect?.width||400,h=rect?.height||200,edge=Math.min(w,h)*(borderWidth*.5); const svg=`<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="${redGradId}" x1="100%" y1="0%" x2="0%" y2="0%"><stop offset="0%" stop-color="#0000"/><stop offset="100%" stop-color="red"/></linearGradient><linearGradient id="${blueGradId}" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stop-color="#0000"/><stop offset="100%" stop-color="blue"/></linearGradient></defs><rect width="${w}" height="${h}" fill="black"/><rect width="${w}" height="${h}" rx="${borderRadius}" fill="url(#${redGradId})"/><rect width="${w}" height="${h}" rx="${borderRadius}" fill="url(#${blueGradId})" style="mix-blend-mode:${mixBlendMode}"/><rect x="${edge}" y="${edge}" width="${w-edge*2}" height="${h-edge*2}" rx="${borderRadius}" fill="hsl(0 0% ${brightness}% / ${opacity})" style="filter:blur(${blur}px)"/></svg>`; return `data:image/svg+xml,${encodeURIComponent(svg)}` };
  const updateMap=()=>feImageRef.current?.setAttribute("href",generateMap());
  useEffect(()=>{updateMap();[[redRef,redOffset],[greenRef,greenOffset],[blueRef,blueOffset]].forEach(([ref,offset])=>{const el=(ref as React.RefObject<SVGFEDisplacementMapElement>).current;if(el){el.setAttribute("scale",String(distortionScale+(offset as number)));el.setAttribute("xChannelSelector",xChannel);el.setAttribute("yChannelSelector",yChannel)}});blurRef.current?.setAttribute("stdDeviation",String(displace))},[width,height,borderRadius,borderWidth,brightness,opacity,blur,displace,distortionScale,redOffset,greenOffset,blueOffset,xChannel,yChannel,mixBlendMode]);
  useEffect(()=>{if(!containerRef.current)return;const ro=new ResizeObserver(()=>requestAnimationFrame(updateMap));ro.observe(containerRef.current);return()=>ro.disconnect()},[]);
  useEffect(()=>{const isWebkit=/Safari/.test(navigator.userAgent)&&!/Chrome/.test(navigator.userAgent);const isFirefox=/Firefox/.test(navigator.userAgent);const div=document.createElement("div");div.style.backdropFilter=`url(#${filterId})`;const frame=requestAnimationFrame(()=>{setSvgSupported(!isWebkit&&!isFirefox&&div.style.backdropFilter!=="");updateMap()});return()=>cancelAnimationFrame(frame)},[]);
  const vars={...style,width:typeof width==="number"?`${width}px`:width,height:typeof height==="number"?`${height}px`:height,borderRadius:`${borderRadius}px`,"--glass-frost":backgroundOpacity,"--glass-saturation":saturation,"--filter-id":`url(#${filterId})`} as CSSProperties;
  return <div ref={containerRef} className={`glass-surface ${svgSupported?"glass-surface--svg":"glass-surface--fallback"} ${className}`} style={vars}><svg className="glass-surface__filter" xmlns="http://www.w3.org/2000/svg"><defs><filter id={filterId} colorInterpolationFilters="sRGB" x="0%" y="0%" width="100%" height="100%"><feImage ref={feImageRef} width="100%" height="100%" preserveAspectRatio="none" result="map"/><feDisplacementMap ref={redRef} in="SourceGraphic" in2="map" result="dispRed"/><feColorMatrix in="dispRed" type="matrix" values="1 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 1 0" result="red"/><feDisplacementMap ref={greenRef} in="SourceGraphic" in2="map" result="dispGreen"/><feColorMatrix in="dispGreen" type="matrix" values="0 0 0 0 0  0 1 0 0 0  0 0 0 0 0  0 0 0 1 0" result="green"/><feDisplacementMap ref={blueRef} in="SourceGraphic" in2="map" result="dispBlue"/><feColorMatrix in="dispBlue" type="matrix" values="0 0 0 0 0  0 0 0 0 0  0 0 1 0 0  0 0 0 1 0" result="blue"/><feBlend in="red" in2="green" mode="screen" result="rg"/><feBlend in="rg" in2="blue" mode="screen" result="output"/><feGaussianBlur ref={blurRef} in="output" stdDeviation=".7"/></filter></defs></svg><div className="glass-surface__content">{children}</div></div>
}
